[appendix]
:appendix-caption: Annex
== HY_Features- SANDRE  Mapping

This is a descriptive mapping for the French National
Service for Water Data and Reference-dataset Management (SANDRE) link:#SANDRE2010[[12\]] on
the basis of the data model describing the national dataset called 'BD
Carthage' link:#SANDRE2017[[14\]]. All element names used correspond to the XML tags
appearing in the data model (and not the attribute names appearing in BD
Carthage).

It is intended to provide an understanding of the basic relationship of
HY_Features concepts and the SANDRE hydrologic feature dictionary for
Hydrography.

Please note that terms for SANDRE are based on French words.

[#annexF_1]
=== Catchment Model

[width="100%",cols="20%,20%,60%",]
|=======================================================================
|
*HY_Features Name*
 |
*SANDRE Name*
 |
*Comment*

|
HY_Catchment
 |
RegionHydro +
OR +
SecteurHydro +
OR +
SousSecteurHydro +
OR +
ZoneHydro
 |
SANDRE makes a distinction between basins and various sub-basins that are
aggregated according to the national hydrographic codification scheme.
All those levels can be seen as being equivalent to 'contracted catchment' in the AHGF, in the sense that there is a contract on the catchment ID that
represents a given catchment.

|
HY_DendriticCatchment
 |
RegionHydro +
OR +
SecteurHydro +
OR +
SousSecteurHydro +
OR +
ZoneHydro
 |
SANDRE: all catchments are dendritic.

|
HY_InteriorCatchment
 |
Not represented
 |
All the 'contracted' catchments identified within the French data model
are considered to flow to a single common outlet.

|
HY_CatchmentAggregate
 |
RegionHydro +
OR +
SecteurHydro +
OR +
SousSecteurHydro
 |
SANDRE: RegionHydro are aggregations of SecteurHydro that are aggregations
of SousSecteurHydro, which in turn are aggregations of ZoneHydro.

|
HY_HydroNexus
 |
NoeudHydrographique
 |
Can be seen as a specific NoeudHydrographique. Thus narrower than
NoeudHydrographique

|
HY_HydroLocation
 |
NoeudHydrographique
 |
Can be seen as a specific NoeudHydrographique. SANDRE does not consider
monitoring devices (ex : hydrometricStation) as a specific
NoeudHydrographique.

|
HY_CatchmentRealization
 |
Not represented
 |
 
|
HY_CatchmentArea
 |
RegionHydro +
OR +
SecteurHydro +
OR +
SousSecteurHydro +
OR +
ZoneHydro
 |
While the polygon representing a catchment might be thought of as an
area, the subset of a DEM or another land cover dataset would be more in
line with the meaning of CatchmentArea.

|
HY_CatchmentDivide
 |
LimiteHydroBassin
 |
LimiteHydroBassin is the boundary of highest catchments in the 
catchment hierarchy. For the French mainland, it basically corresponds to
the six big watersheds that divide it (Loire, Seine, É). Each has a linear
representation.

|
HY_CartographicRealization
 |
Not represented
 |
 
|=======================================================================

[#annexF_2]
=== Hydrographic Network Model

[width="100%",cols="20%,20%,60%",]
|=======================================================================

|
*HY_Features Name*
 |
*SANDRE Name*
 |
*Comment*

|
HY_HydrographicNetwork
 |
Not represented
 |
Within SANDRE Channel and Waterbody are not separated.

SANDRE focuses on HY_ Waterbody(ies) whos identifiers are based on
the HY_Channel containing them.

Such HY_Channel have HY_Waterbody(ies) which are permanent,
intermittent and absent for a long period of time.

Thus permanent identifiers assigned to HY_Channel(s) are usually used as
'proxy' to refer to a given well known body of water (HY_WaterBody).

|
HY_WaterBody
 |
Not represented
 |
 
|
HY_ChannelNetwork
 |
CoursEau +
OR +
TronconHydrographique
 |
SANDRE: CoursEau is an aggregation of TronconHydrographique that is an
aggregation of TronconHydrograElt.

All of them have a linear representation.

|
HY_Depression
 |
EntiteHydroSurface +
OR +
EltHydroSurface
 |
SANDRE: EntiteHydroSurface is an aggregation of EltHydroSurface. Both
have a representation as a surface.

|
HY_Channel
 |
TronconHydrographique +
OR +
TronconHydrograElt +
OR +
EltHydroSurface
 |
SANDRE: CoursEau is aggregation of TronconHydrographique that is an
aggregation of TronconHydrograElt. All of them have a linear
representation.

|
HY_Reservoir
 |
EntiteHydroSurface +
OR +
EltHydroSurface +
OR +
PointEauIsole +
 |
SANDRE: EntiteHydroSurface is an aggregation of EltHydroSurface. Both
have a representation as a surface.

A subset of PointEauIsole can be used in the case that a HY_Reservoir is not
linked to the hydrographic network and is represented by a point.

|
HY_FlowPath
 |
CoursEauPrincipal
 |
Each HY_Catchment equivalent in SANDRE (RegionHydro, É) identifies its
main HY_ChannelNetwork, which provides a hook to providing a HY_FlowPath.

|
HY_LongitudinalSection
 |
Not represented
 |
 
|
HY_CrossSection
 |
Not represented
 |
 
|
HY_WaterBodyStratum
 |
Not represented
 |
 
|
HY_Water_LiquidPhase
 |
Not represented
 |
 
|
HY_Water_SolidPhase
 |
Not represented
 |
 
|=======================================================================

[#annexF_3]
=== Hydrometric Network

[width="100%",cols="20%,20%,60%",]
|=======================================================================
|*HY_Features Name*|*SANDRE Name*|*Comment*
|HY_HydrometricNetwork|Not represented| 
|HY_HydrometricFeature|Not Represented| 
|HY_IndirectPostition|Not represented| 
|=======================================================================