[appendix]
:appendix-caption: Annex
== HY_Features  - AHGF Mapping

This is a descriptive mapping for the Australian Hydrological Geospatial
Fabric (AHGF) link:#BOM2015[[11\]]. It is intended to provide an understanding of the
basic relationship of HY_Features concepts and the AHGF hydrologic
feature implementation.

[#annexC_1]
=== Catchment Model

[width="100%",cols="20%,20%,60%",]
|=======================================================================
|
*HY_Features Name*
 |
*AHGF Name/Class*
 |
*Comment*

|HY_Catchment
 |
Contracted Catchment +

'Base-level' Catchment
 |
A contracted catchment is a catchment identified via ConCatID, which
conceptualizes a holistic unit of hydrology draining to a common outflow
(HY_HydroNexus) with a known identity to which a persistent identifier
is assigned (ConNodeID). This logical catchment may also have a single
inflow, which together with the outflow, define a FlowPath for the
catchment and take part in the AHGF topology tables
(AHGFNodeLinkConnectivityDown and AHGFNodeLinkConnectivityUp). A
catchment may have multiple hydrologic-realizations and is therefore not
restricted to the single geometric representation given by
AHGFContractedCatchment. +

Additionally, AHGF 'base-level' catchments, from which contracted
catchments are derived, can be seen as a second set of conceptualized
units of hydrology draining to a single common outflow and with a single
inflow. These catchments are attributed with a non-persistent identifier (HydroID)
and like contracted catchments, their flow paths take part in AHGF
topology tables (AHGFNetworkConnectivityDown and
AHGFNetworkConnectivityUp). The polygon geometric representation of
these catchments is provided by AHGFCatchment.

|
HY_DendriticCatchment
 |
Contracted Catchment
 |
All contracted catchment
features are constrained to be dendritic in the AHGF. A contracted
catchment's outflow can only be received by a single downstream
contracted catchment.

While sub-sets of AHGF base-level catchments may be dendritic, these catchments are not constrained in the same way as contracted catchments and thus contain non-dendritic relationships.

|
HY_InteriorCatchment
 |
Contracted Catchment +

Subset of 'Base-level' Catchments
 |
Contracted catchments that normally do not contribute flow to a
neighboring contracted catchment or to the coast (i.e. catchments with
potential connections to groundwater or atmospheric systems).

'Base-level' catchments that normally do not contribute flow to a
neighboring base-level catchment or to the coast. These catchments have
no realized FlowPath or HydroNexus.

|
HY_CatchmentAggregate
 |
Collections of Contracted Catchment +

Collections of 'Base-level' Catchments

 |
Sets of non-overlapping dendritic and interior contracted catchment
features aggregated into larger encompassing catchments. Such
aggregations are a fundamental concept in the AHGF and a primary
reason for the creation of the contracted catchments. The AHGF
Topographic Drainage Divisions (AWRADrainageDivision) and River Regions
(RiverRegions) are examples of such aggregations. +

Contracted catchments, derived from collections of 'base-level'
catchments, can themselves be seen as further examples of a catchment
aggregate.

|
HY_HydroNexus
 |
Subset of Contracted Node

AHGFNetworkNode
 |
A hydrologic significant
entity conceptualizing the outflow of a Contracted Catchment. All
contracted nodes in the AHGF are determined by a set of defined business
rules and assigned with persistent identifiers (ConNodeID). A subset of
these contracted nodes act in the role of outflow node (ConNodeID) for
one or more contracted catchment(s) and can also act as an inflow node
(FConNodeID) for zero or one contracted catchment.

Inflow (FromNode) and outflow (ToNode) nodes of 'Base-level' catchments with a realized FlowPath.

|
HY_HydroLocation
 |
AHGFNode +

AHGFNetworkNode

 |
Features in AHGFNode are the subset of contracted nodes, which realize
instances of HY_HydroNexus for contracted catchments. All AHGFNode features therefore act in the role of an outflow node (ConNodeID) for a contracted catchment and may
additionally act in the role of inflow node (FConNodeID) for a
single contracted catchment. Some examples of contracted nodes that
realize hydro nexus in the AHGF are confluences, coastal outlets,
reservoir outlets and monitoring point stream gauges. The AHGF also
defines a specialization of HY_HydroLocation, whereby a collection of
disjoint points (nodes from AHGFNetworkNode) can be used to realize a single nexus, effectively
forming a 'diffused' outflow (or inflow) for a contracted catchment.
Instances of such specialized hydro locations, which are used for
simplification of complex drainage patterns at the boundaries of
contracted catchments, will always include one contracted
node. This representative node is the node used for topological
realization of the hydro nexus. +

AHGFNetworkNode features are further examples of hydro
locations in the AHGF. These are representative outflow (To_Node) and inflow (From_Node) nodes for AHGF 'Base-level' catchments with a realized FlowPath and include the remaining contracted nodes not included in AHGFNode.

|
HY_CatchmentRealization
 |
Feature identified by ConCatID
 |
Any feature, collection of features or topological data identified by a
single ConCatID (contracted catchment). Single instances of
AHGFContractedCatchment and AHGFLink as well as collections of
AHGFNetworkStream, AHGFNetworkNode, AHGFCatchment and AHGFWaterbody features sharing a common ConCatID. +
 +
*Note*: features of subtype AHGFContractedCatchment::NoFlowArea in the
AHGF are special-case un-realizable contracted catchments (normally
small islands) that do not have an associated contracted node (i.e. No
HY_HydroNexus). +
  +
All AHGF 'base-level' catchments have at least one catchment realization,
being a single instance of AHGFCatchment, and many are also realized by
a single AHGFNetworkStream.

|
HY_CatchmentArea
 |
Not represented
 |
An instance HY_CatchmentArea realizes an instance of HY_Catchment as a
catchment area connecting its inflow and outflow and including a plane
surface. Although the polygon representing a catchment might be thought
of as an area, the subset of a DEM or another land cover dataset would
be more in line with the meaning of CatchmentArea as defined by
HY_Features. +
Although not directly represented in the AHGF, the inherent close
relationship between the features of AHGFContractedCatchment,
AHGFCatchment and the DEM (9 second or 1 second) from which they are derived, allow us to postulate a potential realization of a contracted catchment or base-level catchment as the area of the DEM bounded by that contracted or base-level catchment.

|HY_CatchmentDivide
 |
AHGFContractedCatchment +

AHGFCatchment
 |
The AHGFContractedCatchment polygon feature that realizes a contracted
catchment. +

The AHGFCatchment polygon feature that realizes a base-level catchment.

|
HY_CartographicRealization
 |
AHGFMappedStream
 |
The features of AHGFMappedStream within the AHGF Surface Cartography product, 
provide a further realization of both contracted catchments and base-level
catchments. These features, along with the other features in the AHGF Surface Hydrology product are specifically aimed to support cartographic realizations of contracted and base-level catchments. Collections of features from AHGFNetworkStream identified by
a single ConCatID, while a realization of a contracted catchment
themselves, are also attributed with identifiers (AusHydroID) that relate them to corresponding mapped stream features.
|=======================================================================

[#annexC_2]
=== Hydrographic Network

[width="100%",cols="20%,20%,60%",]
|=======================================================================
|
*HY_Features Name*
 |
*AHGF Name/Class*
 |
*Comment*

|
HY_Hydrographic Network
 |
AHGFNetworkStream (subtypes: NetworkFlowSegment & NetworkWaterAreaSegment)

AHGFWaterbody

AHGFMappedStream (subtypes: MappedFlowSegment & MappedWaterAreaSegment)
 |
The collection of AHGFNetworkStream flow segment and water area segment features and on-network AHGFWaterbody features within a particular contracted catchment (identified by a single ConCatID) can be seen to realize that catchment as its hydrographic network.

Similarly, collections of AHGFMappedStream flow segment and water area segment features (related to AHGFNetworkStream via AusHydroID) together with on-network AHGFWaterbody features, provide an alternative (cartographic) representation in the AHGF.

|HY_WaterBody
 |
AHGFNetworkStream
(subtypes: NetworkFlowSegment & NetworkWaterAreaSegment)

AHGFWaterbody

AHGFMappedStream
(subtypes: MappedFlowSegment & MappedWaterAreaSegment)
 |
AHGFNetworkStream flow segment and water area segment features and
AHGFWaterbody features represent water bodies in the AHGF. These
features indicate that there is water contained in some channel or other
containing feature.

Again, alternative representations of flow segment and water area segment features are provided by AHGFMappedStream.

|
HY_ChannelNetwork
 |
AHGFNetworkStream

 |
When AHGFNetworkStream artificial flow segment features are combined with flow segment and water area segment features, this forms the equivalent of a complete channel network in the AHGF. THe collection of such features within a particular contracted catchment (identified by a single ConCatID) can be seen to realize that catchment as its channel network.

Note: AHGFMappedStream artificial flow segment features are NOT equivalent to those in AHGFNetworkStream and have a different usage. 

|
HY_Depression
 |
Not represented

 |
Artificial flow segment features of AHGFNetworkStream are depressions in the land surface, as derived from a particular digital elevation model, where water would theoretically accumulate and flow along channels, connecting up with flow segments and water area segments to form a complete network.  
 
|
HY_Channel
 |
AHGFNetworkStream
(subtype: NetworkArtificialFlowSegment)
 |
Artificial flow segment features from AHGFNetworkStream represent depressions in the land surface (according to particular digital elevation model) where water may flow, even though not normally present. When combined with the other features from the same feature class, this allows representation of the entire logical network, from source to sink (e.g. headwaters to coast).

|
HY_Reservoir
 |
AHGFWaterbody
(subtype: Reservoir)
 |
Features from AHGFWaterbody with the subtype reservoir. A subset of these features have additional attribution linking them to the Australian Bureau of Meteorology's Water Storage product.

|
HY_FlowPath
 |
AHGFLink
 |
Each link feature in AHGFLink realizes a contracted catchment identified
by a single ConCatID. A link is essentially a straight line linking
HY_HyrdoLocation features (AHGFNode), which are represetations of realized
HY_HydroNexus (contracted nodes). Links connect the contracted catchments inflow node to its outflow node.
 
Note: The AHGF currently does not have FlowPath features for contracted
catchments in headwater areas. Such catchments have no represetative inflow node.

|HY_LongitudinalSection |Not represented |

|HY_CrossSection |Not represented |

|HY_WaterBodyStratum |Not represented |

|HY_Water_LiquidPhase |Not represented |

|HY_Water_SolidPhase |Not represented |
|=======================================================================

[#annexC_3]
=== Hydrometric Network

[width="100%",cols="20%,20%,60%",]
|=======================================================================
|
*HY_Features Name*

 |
*AHGF Name/Class*

 |
*Comment*

|HY_HydrometricNetwork |
AHGFNode

(subtype: GhostNode)

AHGFGhostNode

 |In the AHGF, hydrometric features are the combination of AHGFGhostNode features and those AHGFNode ghost node features that realize contracted nodes representing hydrometric stations. Thus, from a AHGF perpective, a hydrometric network can be seen as the collection of logically connected hydrometric ghost node features (from both classes), which provides a specific realization of a contracted catchment (that monitors that catchment).

|HY_HydrometricFeature |
AHGFNode
(subtype: GhostNode)

AHGFGhostNode

 |
Hydrometric features in the AHGF are ghost node monitoring locations that realize contracted catchments either seperately (AHGFNode ghost nodes), or as part of a hydrometric network (AHGFGhostNode + AHGFNode ghost nodes). AHGFNode ghost node features are hydrometric features that act in the role of inflow and outflow hydro nexus for contracted catchments. Ghost node features of the AHGFGhostNode class are reference locations for hydrometric stations for which a hydro nexus has not (yet) been defined.

Note: While hydrometric features were included in earlier versions of
the AHGF, version 3 products were the first to see them included as
realizations acting in the role of inflow and
outflow for contracted catchments.

|HY_IndirectPosition |Not represented 
|Measures are not explicitly included in the AHGF. Note however, that representative locations (AHGFGhostNode) for hydrometric stations without a corresponding hydro nexus are provided 'on river'. Thus, indirect position, as for example, a percentage of distance from a (inflow/outflow) referent along a flowpath, would be relatively straightforward to generate for said features.
|=======================================================================