[appendix]
:appendix-caption: Annex
== HY_Features - NHN Mapping

This is a descriptive mapping for the Canadian National Hydrography
Network link:#NRCAN2017[[13\]]. It is intended to provide an understanding of the basic
relationship of HY_Features concepts and the NHN hydrologic feature
types.

[#annexG_1]
=== Catchment Model

[width="100%",cols="20%,20%,60%",]
|=======================================================================
|
*HY_Features Name*
 |
*NHN Name*
 |
*Comment*

|
HY_Catchment
 |
work unit, or Water Survey of Canada Drainage Areas, Sub-Drainage Areas
and Sub-Sub Drainage Areas
 |
1356 work units covering Canada have been defined. The Water Survey of
Canada has redefined these as a hierarchy with sub-sub-drainage areas
corresponding to the work units. The sub-sub-drainage areas are roughly
comparable to HUC-8's in the NHD. Catchments are also being defined
based on best available data for each of roughly 2200 water gauge
stations across Canada; however, initially these catchments will not
always be aligned to the NHN. So in practical terms, Canada does not
have an equivalent to a HY_Catchment, with its membership in a catchment
coverage and its integrated relationship to a hydrographic network.
(However, British Columbia's Freshwater Atlas (FWA) does have complete
coverage of reach catchments, which were determined algorithmically; the
FWA was the source for NHN in BC. Ontario has also developed catchment
capabilities based on user provided points on a stream.)

|
HY_DendriticCatchment
 |
Not represented
 |
 
|
HY_InteriorCatchment
 |
Not represented
 |
 
|
HY_CatchmentAggregate
 |
Not represented
 |
 
|
HY_HydroNexus
 |
HydroJunction
 |
A hydro junction corresponds to a confluence; however, it is not
specifically related to a catchment (area). If a network linear flow is
thought of as a catchment, then the HydroJunction could be thought of as
a hydro nexus id. NHN does not track catchment or hydro nexus identity.

|
HY_HydroLocation
 |
HydroJunction, man made feature and obstacle.
 |
Since linear referencing is no longer supported, the hydro junctions,
man made features, and obstacles are simply a points that can be thought
of as hydro locations without network location.

|
HY_CatchmentRealization
 |
Not represented
 |
 
|
HY_CatchmentArea
 |
Not represented
 |
 
|
HY_CatchmentDivide
 |
Not represented
 |
 
|
HY_CartographicRealization
 |
A map of work units or Water Survey of Canada drainage areas.
 |
Cartographic realization only applies to maps of work units or Water
Survey of Canada hierarchical drainage areas or the newly defined
drainage areas associated with hydrometric stations.
 
|=======================================================================

[#annexG_2]
=== Hydrographic Network Model

[width="100%",cols="20%,20%,60%",]
|=======================================================================
|
*HY_Features Name*
 |
*NHN Name*
 |
*Comment*

|
HY_HydrographicNetwork
 |
Waterbodies and single line watercourses that correspond to a collection
of network linear flows
 |
The waterbodies and single line watercourses all have corresponding
network linear flows. (Double line streams and lakes are waterbodies
that are also realized by skeleton lines, which are considered as
inferred network linear flows.) As noted earlier though the NHN networks
are not tied to catchments or aggregations of catchments.

|
HY_WaterBody
 |
Waterbodies and single line watercourses.
 |
Waterbody is used specifically for hydrographic features that are
represented by polygons: lakes and double-line streams, defined by banks
and delimiters. Single line watercourses also fall under HY_WaterBody.

|
HY_ChannelNetwork
 |
Not represented
 |
See the comment below under HY_Channel.

|
HY_Depression
 |
Not represented
 |
The NHN has lakes, but does not use the term depression.

|
HY_Channel
 |
Not represented
 |
The NHN does not have channels as distinct from the hydrographic
network. Specifically the properties lists for HY_Channel are not
available.

|
HY_Reservoir
 |
Waterbodies that are reservoirs
 |
The NHN has waterbodies that can be categorized as reservoirs.

|
HY_FlowPath
 |
Network linear flow
 |
Network linear flows are complete, including secondary flows around
islands and constructed flows through wetlands and dams.

|
HY_LongitudinalSection
 |
Not represented
 |
 
|
HY_CrossSection
 |
Not represented
 |
 
|
HY_WaterBodyStratum
 |
Not represented
 |
 
|
HY_Water_LiquidPhase
 |
Not represented
 |
 
|
HY_Water_SolidPhase
 |
Not represented
 |
 
|=======================================================================

[#annexG_3]
=== Hydrometric Network

[width="100%",cols="20%,20%,60%",]
|=======================================================================
|*HY_Features Name*|*NHN Name*|*Comment*
|HY_HydrometricNetwork|Not represented| 
|HY_HydrometricFeature|Not Represented| 
|HY_IndirectPostition|Not represented| 
|=======================================================================