[appendix]
:appendix-caption: Annex
== Conformance Class Abstract Test Suite (Normative)

[#annexA_1]
=== Introduction

These test suites verify the compliance of the conformance targets for
the HY_Features conceptual module with the HY_Features specification.
Each instance of hydrologic feature data is encoded according to a
specific implementation schema, so conformance of a schema or a mapping
to/from such a schema with the abstract specification is defined as a
clear derivation of schema or mapping entities from the concepts,
definitions, and constraints of HY_Features.

[#annexA_2]
=== Conformance class: HY_Features implementation schema equivalence

[width="100%",cols="15%,85%",]
|===
a|*Conformance Class*|*/conf/hy_features_conceptual_model*

a|*Requirements Class*
|link:#_The_HY_Features_conceptual[/req/hy_features_conceptual_model]

a|*Test*|/conf/hy_features_conceptual_model/mapping

a|Requirement
|An implementation schema conforming to HY_Features SHALL implement one
or more feature types defined by the HY_Features UML model in this
standard, including all mandatory properties, associations, and default
values. +
A mapping implementation conforming to HY_Features SHALL implement
mappings between existing feature types and one or more HY_Features
feature types as defined in the HY_Features UML model in this standard,
including all mandatory properties, associations, and default values.

a|Test purpose
|All relevant elements of an implementation schema or data exchange
mapping including hydrologic features are valid implementations of
HY_Features concepts, associations, and constraints.

a|Test method
|Inspect the correspondence between implementation schema or data
exchange mapping elements and the HY_Features model to determine that
all relevant elements are mapped to HY_Features concepts, associations,
and constraints.

a|Test type|Inspection

a|*Test*|/req/hy_features_conceptual_model/GF_Feature

a|Requirement
|Each implemented HY_Features feature type  SHALL be an instance of the
GF_FeatureType (aka FeatureType) «metaclass»

a|Test purpose
|All relevant elements of an implementation schema or data exchange
mapping including hydrologic features are also valid instances of the
GF_FeatureType «metaclass».

a|Test method
|Inspect the definitions of relevant schema or mapping elements to
determine that defined features are valid instances of the
GF_FeatureType «metaclass»..

a|Test type|Inspection
|===