[appendix]
:appendix-caption: Annex
== HY_Features- SANDRE  Mapping

This is a descriptive mapping for the French National
Service for Water Data and Reference-dataset Management (SANDRE) link:#SANDRE2010[[12\]] on
the basis of the data model describing the national dataset called 'BD
Carthage' link:#SANDRE2017[[14\]]. All element name used corresponds to the XML tag
appearing in the data model (not attribute name appearing in BD
Carthage).

It is intended to provide an understanding of the basic relationship of
HY_Features concepts and the SANDRE hydrologic feature dictionary for
Hydrography.

Please notice that terms for SANDRE are based on French words.

[#annexF_1]
=== Catchment Model

[width="100%",cols="20%,20%,60%",]
|=======================================================================
|
*HY_Features Name*
 |
*SANDRE Name*
 |
*Comment*

|
HY_Catchment
 |
RegionHydro +
OR +
SecteurHydro +
OR +
SousSecteurHydro +
OR +
ZoneHydro
 |
SANDRE makes distinction between basins and various sub-basins that are
aggregated according to the national hydrographic codification scheme.
All those levels can be seen as equivalent to 'contracted catchment' in
AHGF in the sense that there is a contract on the catchment ID to
represent a given catchment.

|
HY_DendriticCatchment
 |
RegionHydro +
OR +
SecteurHydro +
OR +
SousSecteurHydro +
OR +
ZoneHydro
 |
SANDRE: all catchments are dendritic

|
HY_InteriorCatchment
 |
Not represented
 |
All the 'contracted' catchments identified within the French data model
are considered to flow to a single common outlet.

|
HY_CatchmentAggregate
 |
RegionHydro +
OR +
SecteurHydro +
OR +
SousSecteurHydro
 |
SANDRE: RegionHydro are aggregation of SecteurHydro that are aggregation
of SousSecteurHydro that are aggregation of ZoneHydro

|
HY_HydroNexus
 |
NoeudHydrographique
 |
Can be seen as a specific NoeudHydrographique. Thus narrower than
NoeudHydrographique

|
HY_HydroLocation
 |
NoeudHydrographique
 |
Can be seen as a specific NoeudHydrographique. SANDRE does not consider
monitoring devices (ex : hydrometricStation) as a specific
NoeudHydrographique

|
HY_CatchmentRealization
 |
Not represented
 |
 
|
HY_CatchmentArea
 |
RegionHydro +
OR +
SecteurHydro +
OR +
SousSecteurHydro +
OR +
ZoneHydro
 |
While the polygon representing a catchment might be thought of as an
area, the subset of a DEM or another land cover dataset would be more in
line with the meaning of CatchmentArea.

|
HY_CatchmentDivide
 |
LimiteHydroBassin
 |
LimiteHydroBassin is the boundary of highest catchments in the 
catchments hierarchy. For France mainland, it basically corresponds to
the 6 big watershed dividing it (Loire, Seine, É) . It has a linear
representation.

|
HY_CartographicRealization
 |
Not represented
 |
 
|=======================================================================

[#annexF_2]
=== Hydrographic Network Model

[width="100%",cols="20%,20%,60%",]
|=======================================================================

|
*HY_Features Name*
 |
*SANDRE Name*
 |
*Comment*

|
HY_HydrographicNetwork
 |
Not represented
 |
Within SANDRE Channel/Waterbody are not disjoint.

SANDRE focuses HY_ Waterbody(ies) which identifiers are based on
HY_Channel containing them.

Those HY_Channel have HY_Waterbody(ies) which are permanent,
intermittent, absent for a long period of time.

Thus permanent identifiers assigned to HY_Channel(s) are usually used as
'proxy' to refer to given well known body of waters (HY_WaterBody).

|
HY_WaterBody
 |
Not represented
 |
 
|
HY_ChannelNetwork
 |
CoursEau +
OR +
TronconHydrographique
 |
SANDRE: CoursEau is an aggregation of TronconHydrographique that is an
aggregation of TronconHydrograElt.

All of them have a linear representation.

|
HY_Depression
 |
EntiteHydroSurface +
OR +
EltHydroSurface
 |
SANDRE: EntiteHydroSurface is an aggregation of EltHydroSurface. Both
have a surfacic representation.

|
HY_Channel
 |
TronconHydrographique +
OR +
TronconHydrograElt +
OR +
EltHydroSurface
 |
SANDRE: CoursEau is aggregation of TronconHydrographique that is an
aggregation of TronconHydrograElt. All of them have a linear
representation.

|
HY_Reservoir
 |
EntiteHydroSurface +
OR +
EltHydroSurface +
OR +
PointEauIsole +
 |
SANDRE: EntiteHydroSurface is an aggregation of EltHydroSurface. Both
have a surfacic representation.

A subset of PointEauIsole can be used in case that a HY_Reservoir is not
linked to the hydrographic network and is represented by a point

|
HY_FlowPath
 |
CoursEauPrincipal
 |
Each HY_Catchment equivalent in SANDRE (RegionHydro, É) identifies its
main HY_ChannelNetwork which provides a hook to providing HY_FlowPath

|
HY_LongitudinalSection
 |
Not represented
 |
 
|
HY_CrossSection
 |
Not represented
 |
 
|
HY_WaterBodyStratum
 |
Not represented
 |
 
|
HY_Water_LiquidPhase
 |
Not represented
 |
 
|
HY_Water_SolidPhase
 |
Not represented
 |
 
|=======================================================================

[#annexF_3]
=== Hydrometric Network

[width="100%",cols="20%,20%,60%",]
|=======================================================================
|*HY_Features Name*|*SANDRE Name*|*Comment*
|HY_HydrometricNetwork|Not represented| 
|HY_HydrometricFeature|Not Represented| 
|HY_IndirectPostition|Not represented| 
|=======================================================================