== Conformance
This standard defines a conceptual model for hydrologic features and
their fundamental relationships. Requirements for conformance with the
conceptual model are defined for two types of implementation targets: a)
implementation schemas for representation of hydrologic data or b)
implementation mappings between terms or concepts from two or more other
existing hydro data schemas based on common intermediary HY_Features
concepts. Any conformant implementations are required to satisfy the
requirements defined in Clause 7 of this document for the requirements
class(es) with which they assert conformance. This is true whether the
implementation is explicit in the case of a schema (such as an OWL/RDF
ontology or XML schema) or implicit in the case of common concepts for a
schema mapping (such as an XSLT rule). The accuracy or detail with which
an external term is mapped to a HY_Features common concept is beyond the
scope of this standard, as is specification of a particular concept
mapping methodology. +

Annexes C-G of this document provide, nevertheless, informative mappings
to and from HY_Features for the following hydro data models: +

* Australian Hydrological Geospatial Fabric (AHGF) [11],
* USGS National Hydrography Dataset Plus (NHD Plus)[10],
* INSPIRE Hydrography theme [2],
* French National Service for Water Data and Reference-dataset
Management (SANDRE) [12],
* Canadian National Hydrography Network (NHN) [13]

These mappings are intended to provide a general understanding of the
correspondence between HY_Features concepts and existing conceptual /
physical models. They are informative with respect to any future mapping
implementations. +

Conformance of implementation targets with this standard shall be
verified using all the relevant tests specified in Annex A (normative)
of this document. The framework, concepts, and methodology for testing,
and the criteria to be met to claim conformance are specified in the OGC
Compliance Testing Policies and Procedures and the https://cite.opengeospatial.org/[OGC Compliance
Testing web site].

All requirements-classes and conformance-classes described in this
document are owned by the HY_Features standard.