== References
The following normative documents contain provisions that, through
reference in this text, constitute provisions of this document. For
dated references, subsequent amendments to, or revisions of, any of
these publications do not apply. For undated references, the latest
edition of the normative document referred to applies.

OGC: OGC Abstract Specification Topic 1, Feature Geometry +
(aka ISO 19107:2003, Geographic Information -- Spatial schema), 2003

OGC: OGC Abstract Specification Topic 2, Spatial referencing by coordinates +
(aka ISO 19111:2007, Geographic Information -- Referencing by
coordinates), 2007

OGC: OGC Abstract Specification Topic 5, Features +
(aka ISO 19101:2002, Geographic Information -- Reference Model), 2002

OGC: OGC Abstract Specification Topic 11, Metadata (aka ISO 19115-1:2014,
Geographic Information -- Metadata -- Fundamentals), 2014

OGC: OGC Abstract Specification Topic 19, Geographic information - Linear
referencing (aka ISO 19148:2012, Geographic Information -- Linear
referencing), 2012

OGC: OGC Abstract Specification Topic 20, Observations and Measurements (aka
ISO 19156:2011, Geographic Information -- Observations and Measurements), 2011

ISO: ISO/TS 19103:2005, Geographic Information -- Conceptual schema language, 2005

ISO: ISO 19108:2006, Geographic Information -- Temporal schema, 2006

ISO: ISO 19109:2006, Geographic Information -- Rules for application schemas, 2006

ISO: ISO 19133:2005, Geographic Information -- Location-based services --
Tracking and navigation, 2005
