== Conventions
This sections provides details and examples for any conventions used in the document. Examples of conventions are symbols, abbreviations, use of XML schema, or special notes regarding how to read the document.

=== Identifiers
The normative provisions in this specification are denoted by the URI

http://www.opengis.net/spec/{standard}/{m.n}

All requirements and conformance tests that appear in this document are denoted by partial URIs which are relative to this base.

[glossary]
=== Symbols (and abbreviated terms)

[glossary]
CHy :: WMO Commission for Hydrology
GML :: Geography Markup Language
GRDC :: Global Runoff Data Centre (GRDC)
GWML2 :: GroundwaterML 2
HDWG :: OGC Hydrology Domain Working Group
ISO :: International Organization for Standardization
OGC :: Open Geospatial Consortium
OWL :: Web Ontology Language
UML :: Unified Modeling Language
WaterML 2 :: WaterML 2.0 – an observation model for hydrology
WIS :: WMO Information System
WIGOS :: WMO Integrated Global Observing System
WMO :: World Meteorological Organization
XML :: eXtensible Markup Language

=== UML notation
Most diagrams that appear in this specification are presented using the Unified Modelling Language (UML) static structure diagram, as described in Sub-clause 5.2 of the OGC Web Services Common Implementation Specification (OGC 04-016r2). UML classes are named in UpperCamelCase and property names in lowerCamelCase.

=== WMO Terminology
The HY_Features model uses—as far as possible—terminology recommended by the WMO Commission for Hydrology for use in the WMO Member countries. The key reference is the "International Glossary of Hydrology" [9], a joint publication of the WMO and the UNESCO. Wherever appropriate, terms from this glossary are applied to the feature concepts in this standard to capture meaning and contextual relationships. The synonym approach widely used in this glossary is interpreted in that way that glossary terms, when explicitly defined as synonyms, were defined as such even if they are not synonymous in every respect. Differences in terminology were explored through reconciling the explicit definitions documented in the glossary with aspects reflected in various data sets and products in use. The accepted terms were augmented with the relationships inferred from other terminology in order to define complex terms that do not clearly distinguish between a specific logical concept and its geometric representation or between a general term and its specific conceptual meaning. The definitions used in the conceptual model described in this standard may be understood as a conceptual refining of the definitions given in the WMO/UNESCO Glossary of Hydrology. 

Though basically rooted in the definitions given in the WMO Glossary of Hydrology, for the purpose of testing the applicability of the conceptual model in the context of surface water hydrology, the definitions applied to hydrologic features defined in this standard refer to surface water. 

Some requirements classes defined in this standard refer to the Scoped Name concept of ISO 19103: CONCEPTUAL SCHEMA. Intended to form a basis for information and data sharing in the community of the WMO member countries, the Scoped Name should reflect a name endorsed by the WMO.

=== Naming convention

The _HY_-prefix used in the UML model follows the ISO naming conventions for UML elements. There is no explicit requirement to use this name in an implementation for the same semantic elements, but it is required to provide an explicit mapping between terminology used and HY_Features to unambiguously indicate hydrologic feature concepts to support unambiguous interpretation in cross-domain applications. While there is not a recognized standard method for recording mappings between abstract element names and implementations; it is expected that system interoperability will be facilitated by making such mappings available as part of a dataset's documentation.
